-- VRMT
CREATE ROLE "$POSTGRES_USER_APP_ADMIN" PASSWORD '$POSTGRES_PASSWORD_APP_ADMIN' NOSUPERUSER CREATEROLE INHERIT LOGIN;

CREATE DATABASE "$POSTGRES_DB_APP";

ALTER DATABASE "$POSTGRES_DB_APP" OWNER TO "$POSTGRES_USER_APP_ADMIN";

ALTER DATABASE "$POSTGRES_DB_APP"
SET
    search_path TO public,
    pre,
    auth,
    api,
    internal,
    cyanaudit;
