-- Grants to CyanAudit
GRANT ALL ON SCHEMA cyanaudit TO "$POSTGRES_USER_APP_ADMIN";

GRANT ALL ON ALL TABLES IN SCHEMA cyanaudit TO "$POSTGRES_USER_APP_ADMIN";

GRANT ALL ON ALL SEQUENCES IN SCHEMA cyanaudit TO "$POSTGRES_USER_APP_ADMIN";

GRANT ALL ON ALL FUNCTIONS IN SCHEMA cyanaudit TO "$POSTGRES_USER_APP_ADMIN";

ALTER DEFAULT PRIVILEGES IN SCHEMA cyanaudit
GRANT ALL ON TABLES TO "$POSTGRES_USER_APP_ADMIN";

ALTER DEFAULT PRIVILEGES IN SCHEMA cyanaudit
GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_APP_ADMIN";

ALTER DEFAULT PRIVILEGES IN SCHEMA cyanaudit
GRANT ALL ON FUNCTIONS TO "$POSTGRES_USER_APP_ADMIN";

-- Avoid public and it"s default setup
REVOKE CONNECT ON DATABASE "$POSTGRES_DB_APP"
FROM
    public;

-- VRMT power role
CREATE ROLE power INHERIT NOLOGIN;

ALTER ROLE power BYPASSRLS;

-- Create access roles with the NOINHERIT attribute
CREATE ROLE anon NOINHERIT NOLOGIN;

CREATE ROLE basic NOINHERIT NOLOGIN;

CREATE ROLE pm INHERIT NOLOGIN;

CREATE ROLE lead INHERIT NOLOGIN;

CREATE ROLE "$POSTGRES_USER_APP" NOINHERIT LOGIN PASSWORD '$POSTGRES_PASSWORD_APP';

-- Setup untrusted extension and function that uses it
-- Schema
CREATE SCHEMA auth;

ALTER SCHEMA auth OWNER TO "$POSTGRES_USER_APP_ADMIN";
