version: "3"

services:
  postgrest:
    environment:
      PGRST_JWT_SECRET: Dummy5ecr3t4D3bug0n1yN0T4Pr0D123

  react-admin:
    image: react-admin:debug
    build:
      args:
        VITE_ENVIRONMENT: DEBUG
        VITE_JWT_SECRET: Dummy5ecr3t4D3bug0n1yN0T4Pr0D123
        VITE_PALETTE_PRIMARY: "#8B8A94"
        VITE_PALETTE_SECONDARY: "#C5C2C8"
