version: "3"

services:
  postgrest:
    environment:
      PGRST_OPENAPI_SERVER_PROXY_URI: https://${HOST}/api
      PGRST_JWT_SECRET: Dummy5ecr3t4D3bug0n1yN0T4Pr0D123
    labels:
      traefik.enable: "true"
      traefik.http.routers.postgrest.entrypoints: websecure
      traefik.http.routers.postgrest.rule: Host(`${HOST}`) && PathPrefix(`/api`)
      traefik.http.routers.postgrest.tls: "true"
      traefik.http.routers.postgrest.tls.certresolver: tls
      traefik.http.services.postgrest.loadbalancer.server.port: 3000
      traefik.http.middlewares.postgrest-stripprefix.stripprefix.prefixes: /api
      traefik.http.routers.postgrest.middlewares: postgrest-stripprefix

  react-admin:
    image: react-admin:debug
    build:
      args:
        VITE_ENVIRONMENT: DEBUG
        VITE_JWT_SECRET: Dummy5ecr3t4D3bug0n1yN0T4Pr0D123
        VITE_PALETTE_PRIMARY: "#8B8A94"
        VITE_PALETTE_SECONDARY: "#C5C2C8"
        VITE_APP_BASE_URI: https://${HOST}
        VITE_API_BASE_URI: https://${HOST}/api
    labels:
      traefik.enable: "true"
      traefik.http.routers.react-admin.entrypoints: websecure
      traefik.http.routers.react-admin.rule: Host(`${HOST}`)
      traefik.http.routers.react-admin.tls: "true"
      traefik.http.routers.react-admin.tls.certresolver: tls
      traefik.http.services.react-admin.loadbalancer.server.port: 80

  swagger:
    environment:
      URLS: '[ { url: "https://${HOST}/api", name: "DTrack" } ]'
      BASE_URL: /swagger
    labels:
      traefik.enable: "true"
      traefik.http.routers.swagger.entrypoints: websecure
      traefik.http.routers.swagger.rule: Host(`${HOST}`) && PathPrefix(`/swagger`)
      traefik.http.routers.swagger.tls: "true"
      traefik.http.routers.swagger.tls.certresolver: tls
      traefik.http.services.swagger.loadbalancer.server.port: 8080

  traefik:
    command:
      - --accessLog=true
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=false
      - --certificatesresolvers.tls.acme.tlschallenge=true
      - --certificatesresolvers.tls.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.tls.acme.storage=/acme/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=net
    image: traefik:2.9
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH}
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.middlewares: traefik-auth
      traefik.http.routers.traefik.rule: Host(`traefik.${HOST}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: tls
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    networks:
      net: {}
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    restart: unless-stopped
    volumes:
      - ./keys/acme:/acme:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
